Add the ability to manually specify addtional CPE entries to be checked.
dependency-check/dependency-check-gradle pull request #361
Opened 2023-11-10 17:03 UTC by gordoninnes

This change allows adding CPEs to be included in analysis for dependencies that might not be picked up during scans.

For example to add in a dependency on PostgresSQL:

`
dependencyCheck {
  additionalCpes {
    postgreSql {
      description = "PostgreSQL"
      cpe = "cpe:2.3:a:postgresql:postgresql:${postgresqlVersion}:*:*:*:*:*:*:*"
     }
  }
}
`

2023-11-15 10:34 UTC, jeremylong commented
I have some larger work to complete in the core library before I can review this PR.

2023-11-16 14:20 UTC, gordoninnes commented
No worries! I appreciate you having a look. I've used these changes locally but would be nice not to have to maintain our own separate build. Hopefully it's a useful feature for others.

2024-01-17 12:32 UTC, jeremylong requested changes
Just a couple of minor changes will help with some of the reports.

2024-01-17 12:32 UTC, jeremylong commented on src/main/groovy/org/owasp/dependencycheck/gradle/tasks/AbstractAnalyze.groovy
> +            dep.setDescription(it.description)
```suggestion
            dep.setDescription(it.description)
            dependency.setDisplayFileName(it.cpe);
            dependency.setSha1sum(Checksum.getSHA1Checksum(it.cpe));
            dependency.setSha256sum(Checksum.getSHA256Checksum(it.cpe));
            dependency.setMd5sum(Checksum.getMD5Checksum(it.cpe));
```

2024-01-17 12:32 UTC, jeremylong commented on src/main/groovy/org/owasp/dependencycheck/gradle/tasks/AbstractAnalyze.groovy
> +import us.springett.parsers.cpe.CpeParser
```suggestion
import org.owasp.dependencycheck.utils.Checksum
import us.springett.parsers.cpe.CpeParser
```

2024-01-17 14:00 UTC, gordoninnes commented
Thanks. I've committed those changes.

2024-01-18 11:15 UTC, jeremylong approved these changes
LGTM

2024-01-18 11:28 UTC, gordoninnes commented
Had to push a fix to get your changes in properly 😞 Can you review again please?

2024-01-21 23:58 UTC, jeremylong approved these changes
LGTM

2024-03-15 09:58 UTC, merged

2024-03-15 09:58 UTC, jeremylong commented
sorry about the delay - this is being released today. I've unfortunately had a ton of other work outside of my OSS contributions consuming my time. Thanks again for the PR.